-- =====================================================
-- Baseline LOCAL — replica o esquema mínimo que já existe
-- no Supabase remoto (tabelas usuario, empresa, enums e a
-- trigger handle_new_user). Todas as instruções são
-- idempotentes (IF NOT EXISTS / OR REPLACE) — rodar isso
-- num projeto que já tem essas estruturas não altera nada.
-- =====================================================

-- Enums --------------------------------------------------
do $$ begin
    create type public.nivelmaturidadefinanceira as enum ('INICIANTE','INTERMEDIARIO','AVANCADO');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.porte as enum ('MEI','MICRO','PEQUENA','MEDIA','GRANDE');
exception when duplicate_object then null; end $$;

do $$ begin
    create type public.regimetributario as enum ('SIMPLES','LUCRO_PRESUMIDO','LUCRO_REAL','MEI');
exception when duplicate_object then null; end $$;

-- Tabela usuario ----------------------------------------
create table if not exists public.usuario (
    id_usuario       uuid primary key references auth.users(id) on delete cascade,
    email            text unique not null,
    nome             text not null,
    senha_hash       text not null default '',          -- senha de fato fica em auth.users
    nivel_maturidade public.nivelmaturidadefinanceira not null default 'INICIANTE',
    data_criacao     timestamptz not null default now(),
    ultimo_acesso    timestamptz
);

-- Tabela empresa ----------------------------------------
create table if not exists public.empresa (
    id_empresa        integer generated by default as identity primary key,
    id_usuario        uuid not null references public.usuario(id_usuario) on delete cascade,
    nome_fantasia     text not null,
    razao_social      text,
    cnpj              bigint unique not null,
    setor             text not null default 'Não informado',
    porte             public.porte,
    regime_tributario public.regimetributario,
    data_criacao      timestamptz not null default now()
);

create unique index if not exists ux_empresa_id_usuario on public.empresa(id_usuario);

-- RLS nas tabelas de domínio ----------------------------
alter table public.usuario enable row level security;
alter table public.empresa enable row level security;

drop policy if exists "usuario_select_self" on public.usuario;
create policy "usuario_select_self"
on public.usuario for select
using (id_usuario = auth.uid());

drop policy if exists "usuario_update_self" on public.usuario;
create policy "usuario_update_self"
on public.usuario for update
using (id_usuario = auth.uid())
with check (id_usuario = auth.uid());

drop policy if exists "empresa_select_own" on public.empresa;
create policy "empresa_select_own"
on public.empresa for select
using (id_usuario = auth.uid());

drop policy if exists "empresa_update_own" on public.empresa;
create policy "empresa_update_own"
on public.empresa for update
using (id_usuario = auth.uid())
with check (id_usuario = auth.uid());

-- =====================================================
-- Trigger handle_new_user: ao criar um usuário em
-- auth.users (via supabase.auth.signUp), popula
-- public.usuario e public.empresa a partir do
-- raw_user_meta_data informado no signup.
-- Esperado raw_user_meta_data:
--   { nome, nome_fantasia, cnpj (string só dígitos), razao_social? }
-- =====================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    v_nome           text := coalesce(new.raw_user_meta_data->>'nome', 'Usuário');
    v_nome_fantasia  text := coalesce(new.raw_user_meta_data->>'nome_fantasia', 'Empresa');
    v_cnpj_str       text := coalesce(new.raw_user_meta_data->>'cnpj', '0');
    v_razao          text := new.raw_user_meta_data->>'razao_social';
    v_cnpj           bigint;
begin
    -- Converte CNPJ. Se falhar, usa 0 (apenas para não quebrar o local).
    begin
        v_cnpj := v_cnpj_str::bigint;
    exception when others then
        v_cnpj := 0;
    end;

    insert into public.usuario (id_usuario, email, nome)
    values (new.id, new.email, v_nome)
    on conflict (id_usuario) do nothing;

    -- Garante CNPJ único: se já existe, soma o id seq pra evitar conflito local
    if exists (select 1 from public.empresa where cnpj = v_cnpj) then
        v_cnpj := v_cnpj + extract(epoch from now())::bigint;
    end if;

    insert into public.empresa (id_usuario, nome_fantasia, razao_social, cnpj)
    values (new.id, v_nome_fantasia, v_razao, v_cnpj)
    on conflict (id_usuario) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();
